<a href="https://colab.research.google.com/github/habibur-rahman-swe/DeepLearningWithKeras/blob/main/DeepLearningWithKeras_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(('Your Tensorflow version: {0}').format(tf.__version__))

Your Tensorflow version: 2.15.0


In [ ]:
# create a constant tensor A
A = tf.constant([[4, 3],
                 [6, 1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [ ]:
# create a variable tensor v
V = tf.Variable([[3, 1],
                 [5, 2]])
# create another tensor B
B = tf.constant([[7, 8],
                 [4, 5]])
print(V)
B

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [5, 2]], dtype=int32)>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]], dtype=int32)>

In [ ]:
# Concatenate columns (2, 2)
AB_concatenated = tf.concat(values=[A, B], axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]], dtype=int32)>

In [ ]:
# Concatenate rows (2, 2)
AB_concatenated = tf.concat(values=[A, B], axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]], dtype=int32)>

In [ ]:
tensor = tf.zeros(shape=[3, 4], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tensor = tf.random.uniform(shape=[3, 4], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.42632663, 0.7947216 , 0.25647342, 0.32245195],
       [0.01210928, 0.8649639 , 0.79825306, 0.46871877],
       [0.62647545, 0.3930987 , 0.37663996, 0.60284245]], dtype=float32)>

In [ ]:
reshaped_tesor = tf.reshape(tensor = tensor, shape = [4, 3])
reshaped_tesor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.42632663, 0.7947216 , 0.25647342],
       [0.32245195, 0.01210928, 0.8649639 ],
       [0.79825306, 0.46871877, 0.62647545],
       [0.3930987 , 0.37663996, 0.60284245]], dtype=float32)>

In [22]:
tensor_as_int = tf.cast(tensor, tf.int32)
tensor_as_int

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [23]:
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [30]:
A = tf.constant([[4, 3],
                 [6, 1]])

V = tf.constant([[4], [2]])

AV = tf.matmul(A, V)
AV

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[22],
       [26]], dtype=int32)>

In [31]:
A = tf.constant([[4, 9],
                 [5, 6],
                 [1, 8]])
rows, columns = A.shape
print('rows', rows, 'columns', columns)

rows 3 columns 2
